# SONAR  Rock VS Mine Classification Problem

### Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Importing Dataset

In [2]:
df = pd.read_csv('Sonar_Data.csv', header = None)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

### Data Preprocessing

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       208 non-null    float64
 1   1       208 non-null    float64
 2   2       208 non-null    float64
 3   3       208 non-null    float64
 4   4       208 non-null    float64
 5   5       208 non-null    float64
 6   6       208 non-null    float64
 7   7       208 non-null    float64
 8   8       208 non-null    float64
 9   9       208 non-null    float64
 10  10      208 non-null    float64
 11  11      208 non-null    float64
 12  12      208 non-null    float64
 13  13      208 non-null    float64
 14  14      208 non-null    float64
 15  15      208 non-null    float64
 16  16      208 non-null    float64
 17  17      208 non-null    float64
 18  18      208 non-null    float64
 19  19      208 non-null    float64
 20  20      208 non-null    float64
 21  21      208 non-null    float64
 22  22      208 non-null    float64
 23  23      208 non-null    float64
 24  24      208 non-null    float64
 25  25      208 non-null    float64
 26  26      208 non-null    float64
 27  27      208 non-null    float64
 28  28      208 non-null    float64
 29  29      208 non-null    float64
 30  30      208 non-null    float64
 31  31      208 non-null    float64
 32  32      208 non-null    float64
 33  33      208 non-null    float64
 34  34      208 non-null    float64
 35  35      208 non-null    float64
 36  36      208 non-null    float64
 37  37      208 non-null    float64
 38  38      208 non-null    float64
 39  39      208 non-null    float64
 40  40      208 non-null    float64
 41  41      208 non-null    float64
 42  42      208 non-null    float64
 43  43      208 non-null    float64
 44  44      208 non-null    float64
 45  45      208 non-null    float64
 46  46      208 non-null    float64
 47  47      208 non-null    float64
 48  48      208 non-null    float64
 49  49      208 non-null    float64
 50  50      208 non-null    float64
 51  51      208 non-null    float64
 52  52      208 non-null    float64
 53  53      208 non-null    float64
 54  54      208 non-null    float64
 55  55      208 non-null    float64
 56  56      208 non-null    float64
 57  57      208 non-null    float64
 58  58      208 non-null    float64
 59  59      208 non-null    float64
 60  60      208 non-null    object
dtypes: float64(60), object(1)
memory usage: 99.2+ KB

In [4]:
df.shape

(208, 61)

In [5]:
df.isna().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [6]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,...,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000
mean,0.029164,0.038437,0.043832,0.053892,0.075202,0.104570,0.121747,0.134799,0.178003,0.208259,...,0.016069,0.013420,0.010709,0.010941,0.009290,0.008222,0.007820,0.007949,0.007941,0.006507
std,0.022991,0.032960,0.038428,0.046528,0.055552,0.059105,0.061788,0.085152,0.118387,0.134416,...,0.012008,0.009634,0.007060,0.007301,0.007088,0.005736,0.005785,0.006470,0.006181,0.005031
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013350,0.016450,0.018950,0.024375,0.038050,0.067025,0.080900,0.080425,0.097025,0.111275,...,0.008425,0.007275,0.005075,0.005375,0.004150,0.004400,0.003700,0.003600,0.003675,0.003100
50%,0.022800,0.030800,0.034300,0.044050,0.062500,0.092150,0.106950,0.112100,0.152250,0.182400,...,0.013900,0.011400,0.009550,0.009300,0.007500,0.006850,0.005950,0.005800,0.006400,0.005300
75%,0.035550,0.047950,0.057950,0.064500,0.100275,0.134125,0.154000,0.169600,0.233425,0.268700,...,0.020825,0.016725,0.014900,0.014500,0.012100,0.010575,0.010425,0.010350,0.010325,0.008525
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

In [7]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [8]:
Rocks = df[df[60] == 'R']
Mines = df[df[60] == 'M']

In [9]:
Rocks.describe()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
count,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,...,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000,97.000000
mean,0.022498,0.030303,0.035951,0.041447,0.062028,0.096224,0.114180,0.117596,0.137392,0.159325,...,0.012311,0.010453,0.009640,0.009518,0.008567,0.007430,0.007814,0.006677,0.007078,0.006024
std,0.014687,0.024011,0.029101,0.031172,0.047217,0.065025,0.065155,0.079772,0.099887,0.113151,...,0.008632,0.007109,0.006174,0.005389,0.005137,0.004773,0.005702,0.004841,0.005114,0.003669
min,0.002500,0.000600,0.002400,0.005800,0.006700,0.010200,0.003300,0.005700,0.007500,0.024200,...,0.000000,0.000800,0.001000,0.001300,0.000600,0.000400,0.000300,0.000300,0.000600,0.001100
25%,0.012300,0.013200,0.014500,0.021100,0.030500,0.059100,0.073100,0.066300,0.074300,0.086000,...,0.006100,0.005200,0.004500,0.005200,0.005000,0.004400,0.003700,0.003100,0.003900,0.003000
50%,0.020100,0.024200,0.028800,0.035000,0.047600,0.079200,0.101500,0.097300,0.105400,0.126400,...,0.010700,0.008800,0.008100,0.008800,0.007700,0.006500,0.006100,0.005200,0.005800,0.005400
75%,0.029100,0.043300,0.050100,0.049400,0.079400,0.116400,0.142200,0.145100,0.159800,0.190800,...,0.015600,0.014100,0.012900,0.013000,0.011400,0.009700,0.010100,0.009200,0.008900,0.007800
max,0.085600,0.163200,0.163600,0.173200,0.256500,0.382300,0.372900,0.411000,0.559800,0.619400,...,0.042600,0.038600,0.026500,0.027100,0.023300,0.024400,0.031600,0.019900,0.029400,0.018000

In [10]:
Mines.describe()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
count,111.000000,111.000000,111.000000,111.000000,111.000000,111.000000,111.000000,111.000000,111.000000,111.000000,...,111.000000,111.000000,111.000000,111.000000,111.000000,111.000000,111.000000,111.00000,111.000000,111.000000
mean,0.034989,0.045544,0.050720,0.064768,0.086715,0.111864,0.128359,0.149832,0.213492,0.251022,...,0.019352,0.016014,0.011643,0.012185,0.009923,0.008914,0.007825,0.00906,0.008695,0.006930
std,0.027074,0.037840,0.044014,0.054497,0.059790,0.052620,0.058179,0.087190,0.122237,0.137366,...,0.013528,0.010770,0.007658,0.008463,0.008404,0.006403,0.005884,0.00746,0.006917,0.005958
min,0.001500,0.001700,0.001500,0.006100,0.007600,0.011600,0.013000,0.005500,0.036800,0.011300,...,0.000900,0.001300,0.000500,0.001000,0.001200,0.000700,0.000900,0.00060,0.000100,0.000600
25%,0.017950,0.019450,0.025250,0.031100,0.045900,0.076950,0.088000,0.098050,0.136950,0.168500,...,0.012500,0.009250,0.005950,0.005600,0.003800,0.004450,0.003700,0.00420,0.003550,0.003100
50%,0.026900,0.035300,0.038600,0.054700,0.074800,0.109100,0.123200,0.129800,0.186400,0.224500,...,0.017100,0.013200,0.010100,0.009600,0.007200,0.007400,0.005700,0.00700,0.007000,0.005300
75%,0.041850,0.059250,0.062500,0.081550,0.111700,0.146300,0.161600,0.181000,0.261050,0.301850,...,0.023850,0.019000,0.016450,0.016050,0.013550,0.012000,0.010650,0.01145,0.011350,0.009200
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.277000,0.332200,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.04400,0.036400,0.043900

### Seperating and Splitting Dataset

In [11]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)

### Training the Logistic Regression Model

In [13]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

LogisticRegression()

### Testing the Model

In [14]:
y_pred = classifier.predict(X_test)

data = {'Actual': y_test, 'Prediction': y_pred}

cmp = pd.DataFrame(data)
cmp

   Actual Prediction
0       M          M
1       M          M
2       R          R
3       R          R
4       M          M
5       R          R
6       M          M
7       R          M
8       R          R
9       R          M
10      R          M
11      M          M
12      R          M
13      R          R
14      R          R
15      R          R
16      R          R
17      R          R
18      M          M
19      R          R
20      M          M

In [15]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred) * 100

80.95238095238095

#### About this model

Accuracy is pretty average as it ranges from 80 to 85% 
mainly because of the size of the dataset. 

It has around 200 rows before splitting which is hard 
to use in a model. 

Also the split size of the dataset can be debated as 
if more data is given to train then model me overfit 
and if less data is given it may underfit.